### ISSUE TITLE
Server not recognized with multiconnect

### ISSUE THREAD

**Issue by obp3ter** [plasmoapp/plasmo-voice#124]
If I connect with my 1.17 client to my 1.16.5 server via multiconnect the server is not recognized as having plasmo-voice.

**Comment by MimicriaUwU** [comment]
> If I connect with my 1.17 client to my 1.16.5 server via multiconnect the server is not recognized as having plasmo-voice.

this is most likely due to the fact that the data packets transmitted between the 1.17 client and the 1.16.5 server may differ in their structure and content (this is my personal assumption). and multiconnect itself cannot transmit other data packets, except the basic ones, for a comfortable game on the server.

**Comment by obp3ter** [comment]
I found this [carpet extension](https://github.com/plusls/plusls-carpet-addition) that added support for multiconnect, that's why I thought it's worth mentioning.

**Comment by Toldoven** [comment]
We need to figure out if there is a way for us to fix this, but if I have to guess, it's something that multiconnect should fix

**Comment by Gaming32** [comment]
multiconnect blocks all plugin packets. You can send them with multiconnect installed by sending them through the multiconnect API.
