### ISSUE TITLE
[Bug] abnormal cpu temperature while using voice chat

### ISSUE THREAD

**Issue by DINNKA** [plasmoapp/plasmo-voice#164]
Ryzen 5600x 4650mhz
Normal cpu temperature at full load is 73 degrees but while im using my mic it somehow heats up to unrealistically high temperatures 79 degrees with 20% cpu load.
I have never seen such a high temperature on my processor even when rendering and the cooler starts humming like an airplane turbine.
I reinstalled minecraft and my mods several time, but after deleting mod config the temperature drops to 75 degrees and the next day it's 79 degrees again. Tried all mod settings, but maybe I missed something?
Temperature demonstration with msi afrerburner: https://youtu.be/v5T0uA7LihA

**Comment by Toldoven** [comment]
https://imgur.com/vUaYuIn

 Maybe you have RNNoise enabled?

**Comment by DINNKA** [comment]
No, already disabled

**Comment by Toldoven** [comment]
Does the same issue appear when using microphone testing?

**Comment by DINNKA** [comment]
Yep the same

**Comment by ShadowFlare** [comment]
Just saw this myself while doing some testing with someone to decide on a voice chat mod. Did the testing on version 1.2.9 on Minecraft 1.18.1.

Checked these in Windows 10 Task Manager with it on the side next to the game. While mic is enabled, both CPU and GPU usage go up a lot, regardless of whether RNNoise noise suppression or compressor/limiter are on or off (neither of these seem to have much effect on CPU/GPU usage, wasn't noticeable). Disabling only mic (and still being able to hear others) returns both to normal. CPU usage is also still a little higher than normal while on push-to-talk at all (compared to being muted), even when not sending voice, but then it goes up to the same extra high CPU/GPU usage as already described while the push-to-talk key is held.

Numbers for reference. I've got a 4-something GHz 8 core 16 thread CPU (Ryzen 4800U), so 6.25% CPU can essentially mean one whole CPU core maxed. With mic muted, Minecraft's CPU usage is around 6 - 7%. On push-to-talk while the key isn't held, CPU is around 10 - 12%. While voice is being transmitted or just in voice activation mode at all, CPU is around 22 - 25%. Those may roughly equate to 1 CPU core with mic muted, 2-ish on push-to-talk while not transmitting voice, and 4 cores when the mic is activated at all. I don't know what the mod could be doing that also increases GPU usage, but it does whenever the mod is using the mic. In a spot where GPU usage was around 40%, with mic in use it went up to around 60% (I've only tested on an integrated GPU so far).

-edit- Forgot to mention when initially posting that when I noticed it, I was using 32 for the distance. Just wanted to mention in case that's relevant in any way (though I'm guessing not, since I don't see the increased CPU/GPU usage when my own mic is muted).

Hoping this gets fixed. I like the mod over Simple Voice Chat and I was considering it for a server, but right now it's looking like I will have to go with Simple Voice Chat so that players with lower-end specs can still use voice chat, until either this is fixed or if I can find a Plasmo Voice version that doesn't have this issue. For reference, I tested that mod as well, and CPU/GPU usage are both normal there, staying in that 6 - 7% range for CPU and 40% for GPU even while the mic is active.

**Comment by ShadowFlare** [comment]
Initially forgot to mention the Minecraft version I was testing on, so I've added that to my post (MC 1.18.1). Also wanted to add that my testing was done while standing still and alone on the server in creative mode and mostly just testing with the Plasmo Voice menu open and clicking the buttons, so the amount of variance in my CPU/GPU readings from moment to moment just from the world state should be negligible.

**Comment by Toldoven** [comment]
Test this version, should no longer have this issue https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.10-client-test

**Comment by DINNKA** [comment]
Thank you, the temperature has become even lower.

**Comment by ShadowFlare** [comment]
Haven't had a chance to make sure the change doesn't negatively affect voice functionality in any way, but it's definitely returned CPU and GPU usage to normal levels for all the test cases I presented above.

**Comment by Toldoven** [comment]
I will close the issue now, please let us know if you'll have this issue again. The version is now released as alpha and available for Forge, with a port for the 1.17 and 1.16 coming when we will make sure that the version is stable. 

https://github.com/plasmoapp/plasmo-voice/releases/tag/1.2.10-alpha
