### ISSUE TITLE
[Question] Can I broadcast sound?

### ISSUE THREAD

**Issue by vitiacat** [plasmoapp/plasmo-voice#213]
I want to create a plugin on the radio that will use the Plasmo Voice API. Is it possible to transmit sound through Plasmo Voice?

**Comment by bottleofench** [comment]
Since version [1.0.12](https://github.com/plasmoapp/plasmo-voice/releases/download/1.0.12-test/plasmovoice-server-1.0.12.jar) PlasmoVoice has an extended API. You can listen to PlayerSpeakEvent and then send the received packet to the players. An example of use, and in general how to work with the API is given [here](https://github.com/plasmoapp/plasmo-voice/blob/main-spigot/README.md).

**Comment by Toldoven** [comment]
https://github.com/plasmoapp/pv-addon-broadcast
