### ISSUE TITLE
ReplayMod can't render the video with voices' audio.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [plasmoapp/plasmo-voice#226]
_I don't know how to report that in plasmoapp/replay-voice-chat, so I did it here._

I have a replay with voices from PlasmoVoice and last version of PlasmoVoice and replay-voice-chat with ReplayMod, but when I render replay as video, I can't hear any voices. Also, if in replay-voice-chat from Simple Voice Chat the audio renders as another file from the video, in this case I didn't find any audio files.

**Comment by Felix14-v2** [comment]
ReplayMod doesn't support audio as it, it just renders a video. You can only replay the sound data, but not merge it with the video. See [#552](https://github.com/ReplayMod/ReplayMod/issues/552#issuecomment-888311477) and [#903](https://github.com/ReplayMod/ReplayMod/issues/903)

**Comment by apehum** [comment]
I've implemented the audio render in AAC format in latest alpha version: https://modrinth.com/mod/pv-addon-replaymod/version/fabric-1.21-2.1.1

Game's audio engine is used to render the audio, so rendered audio should sound exactly like it does in-game. However, because of this approach, it's hard to implement rendering to separate files for each audio source, as the original replay-voice-chat does, so audio is rendered in one single file.

If you have any issues rendering the audio, please open the issue in [pv-addon-replaymod repository](https://github.com/plasmoapp/pv-addon-replaymod).
