### ISSUE TITLE
Add team functions like henkelmax's one

### ISSUE THREAD

**Issue by emielderckx** [plasmoapp/plasmo-voice#32]
henkelmax's simple-voice-chat now has teams, AES encryption and Configurable voice quality. Henkelmax also did a lot of good GUI changes

I think this would also be great to have in plasmo voice

**Comment by Timtaran** [comment]
So then)

**Comment by KPidS** [comment]
We won't just take features from SVC, since we have a different vision for the mod. As of the 1.1.0 version, we got rid of everything we initially took from SVC, and right now our mod is original. I think. If there is still something left, please let us know. Before 1.1.0 it was mostly the interface and audio engine implementation. 

Instead of teams, we are planning to add something like phones or radio. We are planning to make a big update remaking the protocol from scratch, and that is when we are going to add encryption. It's going to take a while though. 

If there are any other features you want to be added, open a new issue describing them.
