### ISSUE TITLE
[Suggestion] Ability to force certain option on the client

### ISSUE THREAD

**Issue by eDexiam** [plasmoapp/plasmo-voice#37]
It'd be nice to have the possiblity to force some options to be ON or OFF on the client.

**Comment by KPidS** [comment]
Can you clarify what options you want to force? I don't think that there are options that shouldn't be optional. You can force push to talk and voice distance, and what else is left? Sound occlusion is a feature that doesn't work well in many situations, so it should be optional. And the only things left are "Show Icons" and Icon Position, and why would you like to force those?

**Comment by eDexiam** [comment]
I was mostly thinking about sound occlusion, I know it is an experimental feature from what I've seen, but for my use case, I'd rather be able to select that for the client, however now that you mention it I'm not sure if the project would benefit from this because as far as I can tell I'm the only one to have a such a use case.

**Comment by eDexiam** [comment]
Actually I just had an idea, the ability to change people's microphone volume with a command would be nice, I know muting is a thing but t can be a nice addition

**Comment by KPidS** [comment]
We can't really do that, since it will be easily bypassable by the client. It requires making a fork of the mod, but It's actually so easy, that anyone with basic programming skills could do that. The majority of players, obviously, won't do that. But if there is one player who can cheat through that, then I don't think that there is much point in doing that.
