### ISSUE TITLE
I don't know what it is and how

### ISSUE THREAD

**Issue by rkfsociety** [plasmoapp/plasmo-voice#40]
[Пн, 17. мая 2021 17:31:02 UTC WARN] java.lang.InstantiationException: Could not find packet with ID -2
[Пн, 17. мая 2021 17:31:02 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:91)
[Пн, 17. мая 2021 17:31:02 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 17:31:03 UTC WARN] java.lang.IllegalStateException: java.io.EOFException
[Пн, 17. мая 2021 17:31:03 UTC WARN] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408)
[Пн, 17. мая 2021 17:31:03 UTC WARN] at su.plo.voice.common.packets.udp.VoiceServerPacket.read(VoiceServerPacket.java:43)
[Пн, 17. мая 2021 17:31:03 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:98)
[Пн, 17. мая 2021 17:31:03 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 17:31:03 UTC WARN] Caused by: java.io.EOFException
[Пн, 17. мая 2021 17:31:03 UTC WARN] at java.io.DataInputStream.readFully(Unknown Source)
[Пн, 17. мая 2021 17:31:03 UTC WARN] at java.io.DataInputStream.readUTF(Unknown Source)
[Пн, 17. мая 2021 17:31:03 UTC WARN] at java.io.DataInputStream.readUTF(Unknown Source)
[Пн, 17. мая 2021 17:31:03 UTC WARN] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406)
[Пн, 17. мая 2021 17:31:03 UTC WARN] ... 3 more
[Пн, 17. мая 2021 17:32:00 UTC WARN] java.lang.InstantiationException: Could not find packet with ID -2
[Пн, 17. мая 2021 17:32:00 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:91)
[Пн, 17. мая 2021 17:32:00 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 17:32:20 UTC WARN] java.lang.InstantiationException: Could not find packet with ID -2
[Пн, 17. мая 2021 17:32:20 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:91)
[Пн, 17. мая 2021 17:32:20 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)

**Comment by howkawgew** [comment]
Note: There is russian lang in data-time column. You can speak russian if you want.

**Comment by howkawgew** [comment]
It's cool, but can you tell us what it is? 
These are the server logs. Is this error always called? What led to this? You can send the full server logs so that we can deal with the error even faster.

**Comment by ThisVanilla** [comment]
оно появляется просто так, даже когда нет никого на сервере
[Пн, 17. мая 2021 21:37:30 UTC WARN] java.lang.InstantiationException: Could not find packet with ID -2
[Пн, 17. мая 2021 21:37:30 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:91)
[Пн, 17. мая 2021 21:37:30 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 21:37:31 UTC WARN] java.lang.IllegalStateException: java.io.EOFException
[Пн, 17. мая 2021 21:37:31 UTC WARN] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408)
[Пн, 17. мая 2021 21:37:31 UTC WARN] at su.plo.voice.common.packets.udp.VoiceServerPacket.read(VoiceServerPacket.java:43)
[Пн, 17. мая 2021 21:37:31 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:98)
[Пн, 17. мая 2021 21:37:31 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 21:37:31 UTC WARN] Caused by: java.io.EOFException
[Пн, 17. мая 2021 21:37:31 UTC WARN] at java.io.DataInputStream.readFully(Unknown Source)
[Пн, 17. мая 2021 21:37:31 UTC WARN] at java.io.DataInputStream.readUTF(Unknown Source)
[Пн, 17. мая 2021 21:37:31 UTC WARN] at java.io.DataInputStream.readUTF(Unknown Source)
[Пн, 17. мая 2021 21:37:31 UTC WARN] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406)
[Пн, 17. мая 2021 21:37:31 UTC WARN] ... 3 more
[Пн, 17. мая 2021 21:39:21 UTC WARN] java.lang.InstantiationException: Could not find packet with ID -2
[Пн, 17. мая 2021 21:39:21 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:91)
[Пн, 17. мая 2021 21:39:21 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 21:39:22 UTC WARN] java.lang.IllegalStateException: java.io.EOFException
[Пн, 17. мая 2021 21:39:22 UTC WARN] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408)
[Пн, 17. мая 2021 21:39:22 UTC WARN] at su.plo.voice.common.packets.udp.VoiceServerPacket.read(VoiceServerPacket.java:43)
[Пн, 17. мая 2021 21:39:22 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:98)
[Пн, 17. мая 2021 21:39:22 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)
[Пн, 17. мая 2021 21:39:22 UTC WARN] Caused by: java.io.EOFException
[Пн, 17. мая 2021 21:39:22 UTC WARN] at java.io.DataInputStream.readFully(Unknown Source)
[Пн, 17. мая 2021 21:39:22 UTC WARN] at java.io.DataInputStream.readUTF(Unknown Source)
[Пн, 17. мая 2021 21:39:22 UTC WARN] at java.io.DataInputStream.readUTF(Unknown Source)
[Пн, 17. мая 2021 21:39:22 UTC WARN] at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406)
[Пн, 17. мая 2021 21:39:22 UTC WARN] ... 3 more

**Comment by ThisVanilla** [comment]
[2021-05-17-6.log](https://github.com/plasmoapp/plasmo-voice/files/6497045/2021-05-17-6.log)

**Comment by ThisVanilla** [comment]
[2021-05-18-1.log](https://github.com/plasmoapp/plasmo-voice/files/6499683/2021-05-18-1.log)

**Comment by rkfsociety** [comment]
сам плагин работает стабильно если что, но откуда эти ошибки я хз, возможно из-за ядра...

**Comment by howkawgew** [comment]
Маловероятно, но это может быть вызвано тем что у вас outdated версия жабы

**Comment by rkfsociety** [comment]
проверил на игровом пк....вроде норм... завтра проверю на серверном.

**Comment by rkfsociety** [comment]
теперь вот такое...
[вт, 18. мая 2021 22:00:50 UTC INFO] rkfsociety lost connection: Disconnected
[вт, 18. мая 2021 22:00:50 UTC WARN] java.lang.reflect.InaccessibleObjectException: Unable to make field java.lang.ThreadLocal$ThreadLocalMap java.lang.Thread.threadLocals accessible: module java.base does not "opens java.lang" to unnamed module @57d5214e
[вт, 18. мая 2021 22:00:50 UTC WARN] at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[вт, 18. мая 2021 22:00:50 UTC WARN] at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[вт, 18. мая 2021 22:00:50 UTC WARN] at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[вт, 18. мая 2021 22:00:50 UTC WARN] at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.boydti.fawe.object.collection.CleanableThreadLocal.iterate(CleanableThreadLocal.java:94)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.boydti.fawe.object.collection.CleanableThreadLocal.getAll(CleanableThreadLocal.java:61)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.sk89q.worldedit.session.request.Request.getAll(Request.java:55)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.sk89q.worldedit.extension.platform.Actor.cancel(Actor.java:235)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.sk89q.worldedit.entity.Player.unregister(Player.java:403)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.sk89q.worldedit.bukkit.BukkitPlayer.unregister(BukkitPlayer.java:417)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.boydti.fawe.bukkit.FaweBukkit.onPlayerQuit(FaweBukkit.java:267)
[вт, 18. мая 2021 22:00:50 UTC WARN] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor782.execute(Unknown Source)
[вт, 18. мая 2021 22:00:50 UTC WARN] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[вт, 18. мая 2021 22:00:50 UTC WARN] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[вт, 18. мая 2021 22:00:50 UTC WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[вт, 18. мая 2021 22:00:50 UTC WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:597)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1847)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:520)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:179)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1512)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1339)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127)
[вт, 18. мая 2021 22:00:50 UTC WARN] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[вт, 18. мая 2021 22:00:50 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:831)
[вт, 18. мая 2021 22:00:50 UTC INFO] Remove client UDP: rkfsociety
[вт, 18. мая 2021 22:01:54 UTC WARN] java.lang.InstantiationException: Could not find packet with ID -2
[вт, 18. мая 2021 22:01:54 UTC WARN] at su.plo.voice.common.packets.udp.PacketUDP.read(PacketUDP.java:91)
[вт, 18. мая 2021 22:01:54 UTC WARN] at su.plo.voice.socket.SocketServerUDP.run(SocketServerUDP.java:92)

**Comment by rkfsociety** [comment]
[latest.log](https://github.com/plasmoapp/plasmo-voice/files/6506176/latest.log)

**Comment by rkfsociety** [comment]
в общем я заменил ядро на paper и обновил java до 16 версии и ошибка пропала.
