### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by Yriokiri** [plasmoapp/plasmo-voice#49]
when clicking things in the setting menu for the mod the game crash with this error

```
The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
Codice di uscita: -1
```

**Comment by KPidS** [comment]
Do you have the last version of the mod as well as the last version of the server?

**Comment by Yriokiri** [comment]
yes, jsut downloaded them now

**Comment by Yriokiri** [comment]
still need to set it up on the server for the port thing but when going in the cliend settings menu sometime it crash

**Comment by KPidS** [comment]
What version are you on? We didn't port the mod to 1.17 yet, because we are waiting for Spigot to release, so we can test everything properly. I'm pretty sure that mod will not work on 1.17. 

If you are on 1.16, try disabling every mod except for Plasmo Voice and check if the crash persists. Maybe there is some conflict. In that case, try to enable each mod one by one until you find the one that causes the conflict.

**Comment by KPidS** [comment]
If none of this helps, then please attach your logs, so we can take a look at them

**Comment by KPidS** [comment]
Was open for almost to weeks now, and there is no response, so I will assume that the issue is fixed now.
