### ISSUE TITLE
mod no install in server 

### ISSUE THREAD

**Issue by Avb-rubns** [plasmoapp/plasmo-voice#51]
When trying to use the mod on the client it shows the message mod not installed on the server but on the panel: Voice UDP server started on /0.0.0.0:25275
version: 1.16.5
server: mohist

**Comment by KPidS** [comment]
Plasmo Voice is meant to be used with vanilla server core, like Spigot and its forks. If you are installing it on mohist, then you should download the [Plasmo Voice Server](https://www.spigotmc.org/resources/plasmo-voice-server.91064/) plugin and install it as a plugin, not as a mod. The mod is for the client-side only. However, we didn't test if it will work, because our mod was never intended to be used with modded servers. I would recommend you [Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat), it's a much better fit for your use case, and it's what Plasmo Voice is based on. 

If you still wish to try and install Plasmo Voice, then you should follow this guide: https://github.com/plasmoapp/plasmo-voice/wiki/How-to-install-Server

If it doesn't work on mohist for whatever reason, we will not fix that, because like I said earlier, Plasmo Voice was never intended to be used with modded servers.
